---
title: "CodeBook"
author: "V.Mahadev"
date: "Friday, August 22, 2014"
output: html_document
---
# Wearable Computing #

##Data Set : Human Activity Recognition Using Smart Phones  ##
###(The Code Book) - Tidydata.txt###

This code book has the following sections

  1. Data Dictionary or Code book  of Tidydata.txt
    
      - This table has four headings (ColumnName, DataType, Description, Values)
 
  2. Data Dictionary or Code book of TidySummaryData.txt
    
      - This is the same as the above dictionary but mean average of each variables has been calculated hence prefixed with mean_
    
  3. Units of Measure
 
  4. Further reading and refernces
 
  5. References and Information Sources (Source Data Information)
  
  6. Acknowledgement
  
  7. License of original data sample publishers
 
###Tidydata.txt - Code Book###

*Attributes:*

```{recho=FALSE}
dd<-read.csv("CodeBookAttributes.csv",head=T)
print(dd)
#require(knitr)
#kable(dd, "html", table.attr = "id=\"datadict_table\"")
#options(markdown.HTML.header = system.file("misc", "datatables.html", package = "knitr"))
#render(DataDict.html)
```


Unit of Measure
==================

*NOTE : All data unless otherwise mentioned are double and all forces and magnitudes are in m/s2 and angles are in radians/second*


Further Reading and references
=================================

Complete technical documentation with sample code available at the following link 

  Sensors Data Acquisition for Android Devices[http://developer.android.com/guide/topics/sensors/sensors_motion.html]
  
  A primer on Co-ordinate system [http://developer.android.com/guide/topics/sensors/sensors_overview.html#sensors-coords]
The gyroscope measures the rate or rotation in rad/s around a device's x, y, and z axis

The units are the same as those used by the acceleration sensor (m/s2), and the coordinate system is the same as the one used by the acceleration sensor.

-If you push the device on the left side (so it moves to the right), the x acceleration value is positive.
-If you push the device on the bottom (so it moves away from you), the y acceleration value is positive.
-If you push the device toward the sky with an acceleration of A m/s2, the z acceleration value is equal to A + 9.81, which corresponds to the acceleration of the device (+A m/s2) minus the force of gravity (-9.81 m/s2).

The stationary device will have an acceleration value of +9.81, which corresponds to the acceleration of the device (0 m/s2 minus the force of gravity, which is -9.81 m/s2).

SOURCE DATA
==============
For further details and readings 
=================================

Data set is built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

For each record it is provided:
======================================

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

The dataset includes the following files:
=========================================

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are **radians/second**. 

Notes: 
======
- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.


For more information about this dataset contact: activityrecognition@smartlab.ws

Acknowledgement
===============

We would like to thank the original researchers for sharing the data of thier research.

If you are planning to use this work or any part of this research do not forget to acknowledge the original publishers

License text has been pasted at the tail of this document for the reference

License:
========
Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.

